name: haru

services:
  ros-publisher:
    image: haru-os
    entrypoint: ["/entrypoint.sh"]
    command: ["rostopic", "pub", "/hello", "std_msgs/String", "data: 'Hello from Docker'", "-r", "1"]
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=${ROS_MASTER_URI}
    network_mode: host
    devices:
      - /dev/snd
      - /dev/bus/usb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  ros-listener:
    image: haru-os
    entrypoint: ["/entrypoint.sh"]
    command: ["rostopic", "echo", "/hello"]
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=${ROS_MASTER_URI}
    network_mode: host
    devices:
      - /dev/snd
      - /dev/bus/usb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  ros-rqt:
    image: haru-os
    entrypoint: ["/entrypoint.sh"]
    command: ["rqt"]
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=${ROS_MASTER_URI}
    network_mode: host
    devices:
      - /dev/snd
      - /dev/bus/usb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
