name: haru

services:
  ros-publisher:
    image: haru-os
    entrypoint: [ "/ros_entrypoint.sh" ]
    command: [ "rostopic", "pub", "/hello", "std_msgs/String", "data: 'Hello from Docker'", "-r", "1" ]
    environment:
      - ROS_MASTER_URI=${ROS_MASTER_URI}
    network_mode: host

  ros-listener:
    image: haru-os
    entrypoint: [ "/ros_entrypoint.sh" ]
    command: [ "rostopic", "echo", "/hello" ]
    environment:
      - ROS_MASTER_URI=${ROS_MASTER_URI}
    network_mode: host

  ros-test:
    image: haru-os
    entrypoint: [ "/ros_entrypoint.sh" ]
    command: [ "rostopic", "pub", "/idmind_tabletop/cmd_move_home", "std_msgs/Empty", "{}" ]
    environment:
      - ROS_MASTER_URI=${ROS_MASTER_URI}
    network_mode: host
