name: haru

services:
  rqt:
    image: haru/haru-os:ros2
    entrypoint: ["/entrypoint.sh"]
    command: ["rqt"]
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
    network_mode: host
    ipc: host
    devices:
      - /dev/snd
      - /dev/bus/usb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  test-publisher:
    image: haru/haru-os:ros2
    entrypoint: ["/entrypoint.sh"]
    command: ["ros2", "topic", "pub", "-r", "1", "/hello", "std_msgs/msg/String", "data: 'Hello from Docker'"]
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
    network_mode: host
    ipc: host
    devices:
      - /dev/snd
      - /dev/bus/usb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
